project:
  type: book
  output-dir: docs

book:
  title: An example tech memo
  subtitle: The subtitle
  date: January 2023
  downloads: [pdf, docx]
  author:
  - name: Jane Doe
    affiliations:
      - id: nwfsc-cb
        name: Northwest Fisheries Science Center
        department: Conservation Biology Division
        address: 
          - 2725 Montlake Boulevard East
          - Seattle, Washington 98112
      - id: uw-safs
        name: University of Washington
        department: School of Aquatic and Fisheries Sciences
  - name: Eva Nováková
    affiliations:
      - ref: uw-safs
  - name: Matti Meikäläinen
    email: matti@jy.fi
    affiliations:
      - name: University of Kemijärvi
        department: Department of Biological and Environmental Science
        address: Kylmäniementie 79, 98120, KEMIJÄRVI, Finland
  - name: Ashok Kumar
    affiliations:
      - name: University of Minnesota
        department: Department of Mathematics
      - name: HØnefoss Institute
        address: R Tradição 35, Portugal 2950-726
  chapters:
    - index.qmd
    - text/Chapter1.qmd
    - text/conclusion.qmd
    - text/references.qmd

  site-url: https://nmfs-opensci.github.io/NOAA-tech-memo-template/
  repo-url: https://github.com/nmfs-opensci/NOAA-tech-memo-template
  repo-actions: [edit, source, issue]
  search: true

bibliography: 
  - text/references.bib

execute:
  echo: false
  code-overflow: wrap
  freeze: auto

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"

metadata-files:
  - _frontmatter.yml
  
