on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up R (needed for Rmd)
        uses: r-lib/actions/setup-r@v2
        
# uncomment if runner changed to unbuntu because the install_deps step was causing problems for gt
#      - name: Install remotes; needed for next line
#        run: Rscript -e 'install.packages(c("remotes"))'
#        
#      - name: Install gt; no binary on cran
#        run: Rscript -e 'install.packages(c("gt"))'

      - name: Install packages (needed for Rmd)
        run: Rscript -e 'remotes::install_deps(quiet = TRUE, upgrade="never", build=FALSE)'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          # Needed if installing tinytex so do not run into GitHub API rate limits
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
